### ISSUE TITLE
Doesn't work require block

### ISSUE THREAD

**Issue by ma3yta** [behzad888/aurelia-view-pipeline#1]
I tried to import markdown file
[https://gyazo.com/fd35efcfb3cd186d3ad35fcfba328d9d](https://gyazo.com/fd35efcfb3cd186d3ad35fcfba328d9d)
I got error in browser [https://gyazo.com/5583c68205389f84eed90ecae85d89f4](https://gyazo.com/5583c68205389f84eed90ecae85d89f4)

**Comment by behzad888** [comment]
You must remove <require> tag from your .html file.
